name: river_tulo_book
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2

#  flutter_staggered_grid_view: ^0.7.0
  bitsdojo_window: ^0.1.5
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.1
  get: ^4.6.5
  image_picker: ^1.0.4
  flutter_native_splash: ^2.2.19
  lunar: ^1.6.1
  webview_flutter: ^4.4.4
#  flutter_inappwebview: ^5.7.2+3
  country_flags: ^2.1.1
  xpath_selector_html_parser: ^3.0.1
#  solar_calculator: ^1.0.3
  timezone: ^0.9.2
  lat_lng_to_timezone: ^0.2.0
#  path_provider: ^2.1.1
#  flutter_cached_pdfview: ^0.4.2
#  flutter_open_chinese_convert: ^0.3.0
#  gif: ^2.3.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/country_state_city_pro/

  fonts:
    - family: font
      fonts:
        - asset: assets/font/font.ttf